FROM node:20-alpine as builder
WORKDIR "/app" 
COPY ./package.json ./
RUN npm install
COPY . .

ARG NODE_ENV
ARG PORT
ARG API_URL

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV API_URL=$API_URL

EXPOSE $PORT
EXPOSE 8000

CMD ["npm", "run", "start:all"]