export type { Profile, ProfileSchema } from './model/types/profile'
export { profileActions, profileReducer } from './model/slice/profileSlice'
export { fetchProfileData } from './model/services/fetchProfileData/fetchProfileData'
export { getProfile } from './model/selectors/getProfile'
export { ProfileCard } from './ui/ProfileCard/ProfileCard'
